name: build-wwiser-nightly

on:
  push:
    branches:
      - master
    paths:
      - "wwiser/**/*.py"
      - "wwiser.py"

  workflow_dispatch:

jobs:
  build-nightly:
    runs-on: windows-2022

    steps:
      # Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      # Generate version
      - name: Get Release Version
        id: release_version
        shell: pwsh
        run: |
          $DateString = Get-Date -Format "yyyyMMdd"
          echo "wwiser_version=$DateString" >> $env:GITHUB_OUTPUT

      # Build app
      - name: Build WWiser
        run: python build.py ${{ steps.release_version.outputs.wwiser_version }}

      # Upload artifact only
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: wwiser-${{ steps.release_version.outputs.wwiser_version }}
          path: ./bin/wwiser.pyz
